# Generated by Django 6.0.5 on 2026-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('dept', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('photo', models.ImageField(upload_to='student_photo/')),
            ],
        ),
        migrations.DeleteModel(
            name='Signinform',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
